### ISSUE TITLE
Auto-starting pickup functionality

### ISSUE THREAD

**Issue by mattgreen** [mattgreen/fogeybot#3]
It'd be cool if the bot could be scheduled to start pickups periodically during prime hours. This would draw more people in vs having a strict schedule.

Need to set:
- How often
- During what hours
- When not to

**Comment by jnovack** [comment]
If the 11th+ person would want to start another pickup right away, or someone in the first 9 people gets impatient, it'll only delay the pickup game.

The main problem is that there's no real ability to announce a pickup game (other than `@everyone`; it's probably better if people harass people to play, rather than the bot harassing people to play.
